### ISSUE TITLE
Casting errors

### ISSUE THREAD

**Issue by sayyad84** [QuiltMC/quiltflower#192]
Hello
Is there a way to call the libraries associated with a class during decompilation so that there are no errors like values not being casted?
![image](https://user-images.githubusercontent.com/57654948/184592834-3be32e70-3e5d-4b59-add3-d31385ca58fe.png)

**Comment by SuperCoder7979** [comment]
Hi, depending on how you're calling Quiltflower you can pass in libraries by including them in the classpath. If you're running through the command line, you can include them by adding `-iec` to the list of options, and then place the jar you would like on the classpath. If you are running through code, you can also add the library classes directly or use `IFernflowerPreferences.INCLUDE_ENTIRE_CLASSPATH`. If you decompiled using another tool, you can check in it's options if it allows you to do this, or otherwise ask them to support this feature.

**Comment by sayyad84** [comment]
Hi,
I did a decompile using -iec but the cast error didn't go away and the ones highlighted in red in the above picture remained. The yellow items are similar to the red items, but the casting is done correctly.

**Comment by SuperCoder7979** [comment]
Hm, in that case it looks like a casting error in the decompiler then. What type and generic args is the `calRow` collection?

**Comment by sayyad84** [comment]
this is more details:
![image](https://user-images.githubusercontent.com/57654948/185762060-91833742-8d22-493a-9877-dccb646c9d13.png)

**Comment by jaskarth** [comment]
This issue seems to be resolved recently in the 1.10 branch, so I'm closing for now- thanks for the report!
