### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "newParameterName" is null

### ISSUE THREAD

**Issue by Jab125** [QuiltMC/quiltflower#296]
Happens with `net/minecraft/world/gen/feature/HugeMushroomFeature`
/*
$VF: Unable to decompile class
Please report this to the Vineflower issue tracker, at https://github.com/Vineflower/vineflower/issues with a copy of the class file (if you have the rights to distribute it!)
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "newParameterName" is null
  at org.jetbrains.java.decompiler.main.ClassWriter.methodToJava(ClassWriter.java:1109)
*/

**Comment by SirYwell** [comment]
By just looking at the code on GH, a wild guess would be that https://github.com/Vineflower/vineflower/blob/master/src/org/jetbrains/java/decompiler/main/ClassWriter.java#L1100-L1105 is flawed, as the name in the MethodParameters attribute is optional. But I don't know if that's the actual cause here.

**Comment by jaskarth** [comment]
I'm unsure how this can manifest, but it is indeed statically possible. It has been fixed, and will land in 1.9.2.
